backend:
  name: git-gateway
  branch: main

media_folder: "_site/images"
public_folder: "/images"

collections:
  - label: Pages
    name: pages
    folder: content
    create: true
    fields:
      - name: layout
        label: Layout
        widget: select
        options:
          - { label: "Een Kolom", value: "een-kolom.njk" }
          - { label: "Twee Kolommen", value: "twee-kolommen.njk" }
      - name: title
        label: Title
        widget: string
      - name: nav_order
        label: Navigatie volgorde
        widget: number
      - name: body
        label: Content
        widget: markdown