backend:
  name: git-gateway
  branch: main

media_folder: "_site/images"
public_folder: "/images"

collections:
  - label: "Pages"
    name: "pages"
    folder: "content"
    create: true
    fields:
      - name: "layout"
        label: "Layout"
        widget: "string"
      - name: "title"
        label: "Title"
        widget: "string"
      - name: body
        label: Content
        widget: markdown