backend:
  name: git-gateway
  branch: main

media_folder: "_site/images"
public_folder: "/images"

collections:
  - name: home
    label: Home
    files:
      - file: content/index.md
        label: Content
        name: index
        fields:
          - { name: content, label: Content, widget: markdown }
  - name: over
    label: Over ons
    files:
      - file: content/over-ons.md
        label: Content
        name: about
        fields:
          - { name: content, label: Content, widget: markdown }
  - name: contact
    label: Contact
    files:
      - file: content/contact.md
        label: Content
        name: contact
        fields:
          - { name: content, label: Content, widget: markdown }
