backend:
  name: git-gateway
  branch: main

media_folder: "_site/images"
public_folder: "/images"

collections:
  - name: pages
    label: Pages
    files:
      - name: home
        label: Home
        file: "content/index.md"
        fields:
          - { name: content, label: Content, widget: markdown, default: '{{file.content | markdownify}}' }
      # - name: over
      #   label: Over ons
      #   file: "content/over-ons.md"
      #   fields:
      #     - { name: content, label: Content, widget: markdown, default: "{{< include file=\"content/over-ons.md\" >}}" }
      # - name: contact
      #   label: Contact
      #   file: "content/contact.md"
      #   fields:
      #     - { name: content, label: Content, widget: markdown, default: "{{< include file=\"content/contact.md\" >}}" }
